// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstx0oajSbtEFDYq4-6p_XYb-FpM9kT_c',
    appId: '1:727606216716:web:ca7f3d63df86bf2b1f4629',
    messagingSenderId: '727606216716',
    projectId: 'sleepwell-43645',
    authDomain: 'sleepwell-43645.firebaseapp.com',
    storageBucket: 'sleepwell-43645.firebasestorage.app',
    measurementId: 'G-N3KX9M216E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPahO_iGHDGuDlj2Bb09zFB0XgLWfM55g',
    appId: '1:727606216716:android:3598fdacad4360af1f4629',
    messagingSenderId: '727606216716',
    projectId: 'sleepwell-43645',
    storageBucket: 'sleepwell-43645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIPooUOugDYP5ajM2lteLvpjhL5RrZ94',
    appId: '1:727606216716:ios:937ca2088daeb7161f4629',
    messagingSenderId: '727606216716',
    projectId: 'sleepwell-43645',
    storageBucket: 'sleepwell-43645.firebasestorage.app',
    iosBundleId: 'com.example.sleepwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIPooUOugDYP5ajM2lteLvpjhL5RrZ94',
    appId: '1:727606216716:ios:937ca2088daeb7161f4629',
    messagingSenderId: '727606216716',
    projectId: 'sleepwell-43645',
    storageBucket: 'sleepwell-43645.firebasestorage.app',
    iosBundleId: 'com.example.sleepwell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDstx0oajSbtEFDYq4-6p_XYb-FpM9kT_c',
    appId: '1:727606216716:web:8ee7ff3042b6255d1f4629',
    messagingSenderId: '727606216716',
    projectId: 'sleepwell-43645',
    authDomain: 'sleepwell-43645.firebaseapp.com',
    storageBucket: 'sleepwell-43645.firebasestorage.app',
    measurementId: 'G-63EH96X5D3',
  );

}